### ISSUE TITLE
fix(readme): alignment of `summary` and `details` HTML tags

### ISSUE THREAD

**Issue by beatrizsmerino** [beatrizsmerino/beatrizsmerino#17]
# fix(readme): alignment of `summary` and `details` HTML tags

| ⏱️ Estimate | 📊 Priority | 📏 Size | 📅 Start | 📅 End |
|---------|-------------|---------|----------|--------|
| 1h      | P2          | XS      | 09-03-2024 | 10-03-2024 |

### Alignment of `summary` and `details` HTML tags

| Current | Expected |
|:------:|:------:|
| <img width="400" alt="Inline elements (span) fix the alignment on the same line" src="https://github.com/beatrizsmerino/beatrizsmerino/assets/14045148/be53e34d-4099-40bc-80a5-dce777c4e99f" /> | <img width="400" alt="Block elements (h1, h2, div) take 100% width causing misalignment" src="https://github.com/beatrizsmerino/beatrizsmerino/assets/14045148/b48d38c9-cee1-4d51-ae7d-14284d67dbcb" /> |

## 📝 Summary

- In the README dropdowns created with `<details>` and `<summary>` HTML tags, the arrow, icon and title are not aligned horizontally on the same line
- The elements should be displayed inline on a single row for a clean, professional appearance

## 💡 Why this bug?

- The default rendering of `<summary>` elements in GitHub markdown may not properly align inline elements (icons, text) depending on the HTML structure used
- The arrow indicator, icon image and title text need specific CSS or HTML adjustments to display on the same line

## ✅ Expected behavior

- The disclosure arrow, icon and title text in each `<summary>` element should be aligned horizontally on the same line
- The dropdown should expand/collapse correctly when clicked

## 📋 Steps

- [x] Update the `<summary>` tag structure to ensure all inline elements (arrow, icon, title) are horizontally aligned
- [x] Use the approach described in the referenced gists and StackOverflow solutions
- [x] Test the rendering on the GitHub profile page

## 🧪 Tests

- [x] Arrow, icon and title are aligned on the same line in all `<summary>` elements
- [x] Dropdowns expand and collapse correctly
- [x] Layout looks consistent across different browsers
- [x] No visual regressions in the README

### Files modified

- [x] `README.md`

### Documentation

- [https://gist.github.com/scmx/eca72d44afee0113ceb0349dd54a84a2](https://gist.github.com/scmx/eca72d44afee0113ceb0349dd54a84a2)
- [https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab)
- [https://stackoverflow.com/questions/31562552/collapsible-header-in-markdown-to-html](https://stackoverflow.com/questions/31562552/collapsible-header-in-markdown-to-html)

**Comment by beatrizsmerino** [comment]
```html
<details id="presentation" open="true">
	<summary>
		<span>👋_Presentation</span>
	</summary>
	<div>Content ...</div>
</details>
```

**Comment by beatrizsmerino** [comment]
## Solution

This could solve the problem but no styles can be applied in any way.

```css
summary > * {
    display: contents;
}
```

I have converted the text and icon to fixed-width SVG images with the online tool: https://readme-typing-svg.demolab.com.

Commit with the solution: 8cbc78299c15623ee5be7b7756113234db89aa8d

**Comment by webdev23** [comment]
Yes there is many ways to solve that with CSS, unfortunately we can't use CSS.

Those little `details` bugs me out too :)

**Comment by beatrizsmerino** [comment]
Solved!
